#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

progname=$0

shopt -s nullglob globstar

warn() {
    local line
    for line in "$@"; do
        echo "$progname: $line" 1>&2
    done
}

error() {
    warn "$@"

    exit 1
}

args=$(
    getopt \
        --options f:t:Fivm:H:: \
        --longoptions from:,to:,force,interactive,verbose,directory-mode:,history:: \
        --name "$0" \
        -- "$@"
)

eval set -- "$args"

from=${WEAVE_FROM:-$PWD}
to=${WEAVE_TO:-$HOME}
lnflags=()
mkdirflags=()
rmflags=()

dohist=0
histpath=.weavehist

if [[ -v WEAVE_HIST ]]; then
    dohist=1
    if [[ -n $WEAVE_HIST ]]; then
        histpath=$WEAVE_HIST
    fi
fi

while true; do
    case "$1" in
    -f | --from)
        from=$2
        shift 2
        ;;
    -t | --to)
        to=$2
        shift 2
        ;;
    -F | --force)
        lnflags+=(--force)
        rmflags+=(--force)
        shift
        ;;
    -i | --interactive)
        lnflags+=(--interactive)
        rmflags+=(--interactive)
        shift
        ;;
    -v | --verbose)
        lnflags+=(--verbose)
        mkdirflags+=(--verbose)
        rmflags+=(--verbose)
        shift
        ;;
    -m | --directory-mode)
        mkdirflags+=(--mode "$2")
        shift 2
        ;;
    -H | --history)
        dohist=1
        if [[ -n $2 ]]; then
            histpath=$2
        fi
        shift 2
        ;;
    --)
        shift
        break
        ;;
    esac
done

from=$(realpath --strip -- "$from")
to=$(realpath --strip -- "$to")

if (($# > 0)); then
    choices=("$@")
else
    choices=()
    for dir in "$from"/*/; do
        choices+=("$(basename -- "$dir")")
    done
fi

shopt -s dotglob

hist=()
if ((dohist)); then
    if [[ -r $histpath ]]; then
        while IFS= read -r link; do
            hist+=("$link")
        done <"$histpath"
    fi

    : >"$histpath"
fi

histupdate() {
    if (($# != 1)); then
        error 'invalid number of arguments'
    fi

    local link=$1
    
    local newhist=()

    if ((dohist)); then
        for entry in "${hist[@]}"; do
            if [[ $entry != "$link" ]]; then
                newhist+=("$entry")
            fi
        done
        hist=("${newhist[@]}")
        echo "$link" >>"$histpath"
    fi
}

for choice in "${choices[@]}"; do
    prefix=$from/$choice
    for target in "$prefix"/**/*; do
        if [[ ! -f $target ]]; then
            continue
        fi

        link=$to${target#"$prefix"}
        parent=$(dirname -- "$link")

        if [[ -L $link && "$(realpath -- "$link")" == "$target" ]]; then
            histupdate "$link"
            continue
        fi
        
        mkdir --parents "${mkdirflags[@]}" -- "$parent"
        ln --symbolic "${lnflags[@]}" -- "$target" "$link"
        histupdate "$link"
    done
done

for link in "${hist[@]}"; do
    if [[ -L "$link" && ! -f "$link" ]]; then
        rm "${rmflags[@]}" -- "$link"
    fi
done
